[project]
name = "consumeai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "addict>=2.4.0",
    "ollama>=0.6.0",
    "omegaconf>=2.3.0",
    "python-dotenv>=1.1.1",
]
